#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
energy_sha="92923fb62c5db21efa9e24997670fa4113b8567e"
ifip_sha="4738a4fae322a84b662bb9216f4bc982d5d92402"
energy="https://raw.githubusercontent.com/Meamarian/EnergyTracer/${energy_sha}"
ifip="https://raw.githubusercontent.com/Meamarian/Hybrid_P4_IFIP_WMNC_24/${ifip_sha}"
get() {
    local url="$1"
    local out="$2"
    mkdir -p "$(dirname "$out")"
    curl -fL --retry 3 --retry-delay 1 "$url" -o "$out"
}
get "$energy/DPDK/gNB_power_aware.c" "$root/dpdk/upstream/gNB_power_aware.c"
get "$energy/README.md" "$root/EnergyTracer/upstream/README.md"
get "$energy/EnergyTracer/README.md" "$root/EnergyTracer/upstream/RUN_GUIDE.md"
get "$energy/EnergyTracer/ltracer.py" "$root/EnergyTracer/tools/ltracer.py"
get "$energy/EnergyTracer/dtracer.py" "$root/EnergyTracer/tools/dtracer.py"
get "$energy/EnergyTracer/sync.py" "$root/EnergyTracer/tools/sync.py"
get "$energy/EnergyTracer/chart.py" "$root/EnergyTracer/tools/chart.py"
get "$energy/EnergyTracer/Validators/checker.py" "$root/EnergyTracer/tools/Validators/checker.py"
get "$energy/EnergyTracer/Validators/rapl_gran.py" "$root/EnergyTracer/tools/Validators/rapl_gran.py"
get "$energy/EnergyTracer/Validators/stats.py" "$root/EnergyTracer/tools/Validators/stats.py"
get "$energy/EnergyTracer/Validators/sync_checker.py" "$root/EnergyTracer/tools/Validators/sync_checker.py"
get "$energy/Trex_Traffic/test_burst_dist.py" "$root/EnergyTracer/traffic/test_burst_dist.py"
get "$ifip/p4_src/main.p4" "$root/p4/upstream/main.p4"
get "$ifip/p4_src/with_cloning/main.c" "$root/p4/upstream/main_clone.p4"
get "$ifip/config/base.p4cfg" "$root/p4/upstream/base.p4cfg"
get "$ifip/config/config_generator/p4_cfg_generator.py" "$root/p4/upstream/p4_cfg_generator.py"
get "$ifip/smartnic_setup/README.md" "$root/smartnic/upstream/README.md"
get "$ifip/smartnic_setup/setup.sh" "$root/smartnic/upstream/setup.sh"
get "$ifip/smartnic_setup/push_pifrte.sh" "$root/smartnic/upstream/push_pifrte.sh"
get "$ifip/smartnic_setup/stop.sh" "$root/smartnic/upstream/stop.sh"
get "$ifip/smartnic_setup/tail_log.sh" "$root/smartnic/upstream/tail_log.sh"
get "$ifip/smartnic_setup/virtual_interface_binding.txt" "$root/smartnic/upstream/virtual_interface_binding.txt"
get "$ifip/multiple_smartnic/sevice_mng_guide.txt" "$root/smartnic/upstream/service_mng_guide.txt"
get "$ifip/Trex_TG/test_perf_1.py" "$root/traffic/upstream/test_perf_1.py"
get "$ifip/Trex_TG/test_perf_2.py" "$root/traffic/upstream/test_perf_2.py"
get "$ifip/Trex_TG/test_perf_3.py" "$root/traffic/upstream/test_perf_3.py"
get "$ifip/Trex_TG/test_perf_4.py" "$root/traffic/upstream/test_perf_4.py"
get "$ifip/Trex_TG/getting_stats/get_stats.py" "$root/traffic/upstream/get_stats.py"
python3 "$root/scripts/prepare_dpdk.py"
